BEGIN;
CREATE TABLE IF NOT EXISTS incidents (
        incident_number NUMERIC PRIMARY KEY,
        exposure_number NUMERIC ,
        id NUMERIC NOT NULL,
        address VARCHAR ,
        incident_date VARCHAR,
        call_number NUMERIC ,
        alarm_dttm VARCHAR ,
        arrival_dttm VARCHAR ,
        close_dttm VARCHAR ,
        city VARCHAR ,
        zipcode VARCHAR ,
        battalion VARCHAR(10),
        station_area VARCHAR(10) ,
        box VARCHAR,
        suppression_units NUMERIC ,
        suppression_personnel NUMERIC ,
        ems_units NUMERIC ,
        ems_personnel NUMERIC ,
        other_units NUMERIC ,
        other_personnel NUMERIC ,
        first_unit_on_scene VARCHAR,
        estimated_property_loss NUMERIC ,
        estimated_contents_loss NUMERIC ,
        fire_fatalities NUMERIC ,
        fire_injuries NUMERIC ,
        civilian_fatalities NUMERIC ,
        civilian_injuries NUMERIC ,
        number_of_alarms NUMERIC ,
        primary_situation VARCHAR ,
        mutual_aid VARCHAR,
        action_taken_primary VARCHAR,
        action_taken_secondary VARCHAR,
        action_taken_other VARCHAR,
        detector_alerted_occupants VARCHAR,
        property_use VARCHAR,
        area_of_fire_origin VARCHAR,
        ignition_cause VARCHAR,
        ignition_factor_primary VARCHAR,
        ignition_factor_secondary VARCHAR,
        heat_source VARCHAR,
        item_first_ignited VARCHAR,
        human_factors_associated_with_ignition VARCHAR,
        structure_type VARCHAR,
        structure_status VARCHAR,
        floor_of_fire_origin NUMERIC,
        fire_spread VARCHAR,
        no_flame_spread VARCHAR,
        number_of_floors_with_minimum_damage NUMERIC,
        number_of_floors_with_significant_damage NUMERIC,
        number_of_floors_with_heavy_damage NUMERIC,
        number_of_floors_with_extreme_damage NUMERIC,
        detectors_present VARCHAR,
        detector_type VARCHAR,
        detector_operation VARCHAR,
        detector_effectiveness VARCHAR,
        detector_failure_reason VARCHAR,
        automatic_extinguishing_system_present VARCHAR,
        automatic_extinguishing_sytem_type VARCHAR,
        automatic_extinguishing_sytem_perfomance VARCHAR,
        automatic_extinguishing_sytem_failure_reason VARCHAR,
        number_of_sprinkler_heads_operating NUMERIC,
        supervisor_district VARCHAR,
        neighborhood_district VARCHAR,
        point VARCHAR,
        data_as_of VARCHAR ,
        data_loaded_at VARCHAR
    );
COMMIT;

