--COPY incidents FROM STDIN WITH CSV HEADER DELIMITER E',' QUOTE E'\'' NULL AS 'null';

--COPY Incidents FROM STDIN WITH CSV HEADER DELIMITER E',' QUOTE E'\'' NULL AS 'null';
--COPY Incidents FROM STDIN WITH (FORMAT 'csv', HEADER, DELIMITER E'\t', NULL 'null', FORCE_QUOTE *);
/*
COPY Incidents FROM STDIN WITH CSV HEADER DELIMITER '\t'  QUOTE '\'' NULL AS 'null';
*/  


